### ISSUE TITLE
Question: how to get the node's token and internal type

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/client-go#100]
Before:

```go
uast.Node.Token
uast.Node.InternalType
uast.Node.StartPosition
uast.Node.EndPosition
```

After (Annotated mode)?..

**Comment by dennwc** [comment]
```golang
token := uast.TokenOf(node)

typ = uast.TypeOf(node)

pos := uast.PositionsOf(node)
start := pos.Start()
end := pos.End()
```
See https://github.com/bblfsh/sdk/issues/318 regarding the token reliability.

**Comment by vmarkovtsev** [comment]
:+1:

**Comment by dennwc** [comment]
Reopening until documentation is updated

**Comment by bzz** [comment]
Where in docs do you @dennwc think this and #99 does belong to? The only I can think of right now is https://docs.sourced.tech/babelfish/using-babelfish/grpc-usage-example.

Rationale - it seems too advanced for https://docs.sourced.tech/babelfish/using-babelfish/clients but https://docs.sourced.tech/babelfish/using-babelfish/advanced-usage does not have any code.

Please, let me know what would be the best place and I'll be happy to add it there.

**Comment by juanjux** [comment]
Outside of the go client godoc, probably the right place would be the go-client readme example trough since the clients documentation page already has a Go example it won't hurt to add this there too. I'll open PRs for both projects.

**Comment by vmarkovtsev** [comment]
@dennwc @bzz I've got

```
cannot use element (type nodes.Node) as type nodes.Object in argument to "gopkg.in/src-d/hercules.v7/vendor/gopkg.in/bblfsh/sdk.v2/uast".TokenOf: need type assertion
```

So to get the token you need to

```go
uast.TokenOf(node.(nodes.Object))
```

**Comment by juanjux** [comment]
Yes. That's how I needed to document it. It's certainly not beautiful.

**Comment by dennwc** [comment]
Let's change it to `node.Node` instead of `nodes.Object` and document that it returns an empty string if it's not an object.

**Comment by creachadair** [comment]
Does #363 resolve this issue?

**Comment by vmarkovtsev** [comment]
It seems so. I will use the new release in Hercules and report any left problems separately, ok?
