### ISSUE TITLE
Unsupported language using C# as driver

### ISSUE THREAD

**Issue by erizocosmico** [bblfsh/client-go#108]
If you set `C#` as the language, bblfsh says "unsupported language", but if you use `csharp` it works. The thing is, `C#` is what enry returns, so it should work on bblfsh as well.

**Comment by smola** [comment]
Related discussions:
https://github.com/bblfsh/bash-driver/issues/39
https://github.com/bblfsh/documentation/issues/191

**Comment by bzz** [comment]
Until we have a language aliases support https://github.com/bblfsh/bash-driver/issues/39#issuecomment-442539768 - we better of keeping our current re-mapping strategy that is [already in-place for C#](https://github.com/bblfsh/bblfshd/blob/1c851f155018c126de3b5ed5af9ab2f926755b4a/daemon/language.go#L11)

This is already working for the case of C# + bblfshd lang detection. Going to add the same re-mapping for case of user-provided language name.

**Comment by bzz** [comment]
@erizocosmico on
> If you set `C#` as the language, bblfsh says "unsupported language",

If you could be so kind and provide an API call and exact error message on this failure in `C#` case -
that would help to make sure I did not miss it in the fix.

So far I got 

```
$ bblfsh-cli -l 'C#' ./smth.cs
couldn't parse ./smth.cs: rpc error: code = Unknown desc = unexpected error: runtime failure: missing driver for language "C#"
```

Would that be the same case you are talking about, right?

**Comment by erizocosmico** [comment]
Yes. That's the same issue

**Comment by bzz** [comment]
Will be part of the next v2.12.0 release scope
