### ISSUE TITLE
How to calculate the number of immediate children of the node?

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/client-go#109]
Before:

```go
len(node.Children)
```

After?..

**Comment by dennwc** [comment]
Fast answer:
```golang
var n int
switch node := node.(type) {
case nodes.Array:
  n = len(node)
case nodes.Object:
  n = len(node)
}
```
Will add a helper for it.

**Comment by vmarkovtsev** [comment]
Thanks!

**Comment by juanjux** [comment]
@dennwc ping me when you add the helper and I'll add it to the documentation's client example.

**Comment by dennwc** [comment]
I will reopen this one so I don't forget.

**Comment by vmarkovtsev** [comment]
@dennwc This does not work the way I expect it to work. My root node is a `nodes.Object` and it returns the size of it's `map[string]whatever` which is always 4. I need it to return the number of items inside "body".

**Comment by vmarkovtsev** [comment]
So the corrected code is

```go
var numChildren int
	switch node := uast.(type) {
	case nodes.Array:
		numChildren = len(node)
	case nodes.Object:
		numChildren = len(node["body"].(nodes.Array))
	}
```

**Comment by dennwc** [comment]
Yes, the last option is correct, although there might be other fields except `body`.
