### ISSUE TITLE
How to map nodes?

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/client-go#112]
I need to maintain a mapping from `nodes.Node` to values, however, it is an interface type and hence cannot be hashed. When I used to work with `*uast.Node`, I did not have this problem because I worked with pointers. What is the recommended way to map nodes in v2?

**Comment by dennwc** [comment]
We have a special function that generates comparable keys:
```golang
m := make(map[nodes.Comparable]T)
k := nodes.UniqueKey(node)
m[k] = t
```
SDK v3 will use pointers for nodes again.

**Comment by vmarkovtsev** [comment]
Awesome, this resolved my task.
