### ISSUE TITLE
package name doesn't match import path

### ISSUE THREAD

**Issue by campoy** [bblfsh/client-go#28]
It's non idiomatic to define a package with a name differing the last component of its import path.

When importing `"gopkg.in/bblfsh/client-go.v2"` the identifier added to the namespace of the program is unexpectedly `bblfsh`.

Is there any good reason for this that I'm missing out?

**Comment by abeaumont** [comment]
You're right, and I guess it's probably for consistency across clients (all of them providing a `bblfsh` package).
cc: @mcuadros

**Comment by mcuadros** [comment]
The main reason is that having a package just called `client` maybe doesn;'t make sense, in the other doesn't make sence either having a repo called `bblfsh/bblfsh-go-client` in the organization. Is just style. 

The name of this repisitory is based for example in the name of `k8s.io/client-go`, but in this case the root of the repository doesn't contain any code, and old the code is contained in a package called `kubernetes`, maybe for the next version we can follow this patern too.

**Comment by bzz** [comment]
Thank you for explanation, @mcuadros !

Going to close this one, if no objections, as there was no further discussion for a while now and nothing actionable seems to be left.

Please, feel free to re-open though, if that somehow is not the case.
