### ISSUE TITLE
Installation instructions in the readme

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/client-go#30]
I followed the installation instructions listed in the README and they worked. However, the first command fails with

```
# gopkg.in/bblfsh/client-go.v2/tools
In file included from ../../bblfsh/client-go.v2/tools/filter.go:14:0:
./bindings.h:8:18: fatal error: uast.h: No such file or directory
compilation terminated.
```

I understand that this is intended because `make deps` fixes it. Should we put a notice there in the README that the first command will fail and it is normal?

**Comment by juanjux** [comment]
#34 should fix that. Thanks for reporting.
