### ISSUE TITLE
Installation process should not require make dependencies

### ISSUE THREAD

**Issue by erizocosmico** [bblfsh/client-go#49]
Go libraries are expected to be perfectly buildable after doing `go get`, which is not the case for this library, since it cannot be used before making `make dependencies`. This makes transitively all projects using it require a step to make the dependencies of this library, which is a pain.

Isn't there a way to avoid this step either by including whatever it's downloading in a bindata or something?

**Comment by dennwc** [comment]
Yes, we can definitely push `libuast` to the repository. But for most Go libraries that use cgo it's okay to require an additional step to pull C dependencies.

**Comment by bzz** [comment]
AFAIK fetching native dependencies is something that all clients do these days. But the process of doing so have to be a bit more bullet-proof - here is an example when current process breaks the clients https://github.com/bblfsh/client-go/issues/50 which I guess would be avoided on @erizocosmico suggestion.

@dennwc I'm not Golang expert, but does 
> Go libraries that use cgo it's okay to require an additional step to pull C dependencies.

contradict to

> Go libraries are expected to be perfectly buildable after doing go get, which is not the case for this library 

?

**Comment by bzz** [comment]
As `go get github.com/src-d/gitbase/cmd/gitbase` also fails now with 

```
# github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools
In file included from ../../gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/bindings.go:45:
./bindings.h:13:10: fatal error: 'libuast/uast.h' file not found
#include "libuast/uast.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

+1 for including libuast go-client.

**Comment by erizocosmico** [comment]
@bzz we updated the README on how to do that https://github.com/src-d/gitbase#installing-from-source
