### ISSUE TITLE
Installation fails to compile libuast due network failure

### ISSUE THREAD

**Issue by bzz** [bblfsh/client-go#50]
go-client user's [CI fails](https://github.com/bblfsh/dashboard/pull/105) on libuast building step i.e in https://travis-ci.org/bblfsh/dashboard/builds/361636871 with

```
./bindings.h:13:26: fatal error: libuast/uast.h: No such file or directory
 #include "libuast/uast.h"
                          ^
compilation terminated.
```

on what actually looks like a [networking failure](https://github.com/bblfsh/client-go/blob/274b551eb1e5a7a3e4aff84d8ee1a56feb799107/Makefile#L33) on fetching libuast. Full build log [here](https://pastebin.com/BZRx64mD).

It would be nice to be more explicit and check if download fails, and then retry i.e something like this [helper in Gemini]( https://github.com/src-d/gemini/blob/f0fd111e3c0dfa60629ccfd2b4193cb6b203e01d/scripts/get_apache_spark.sh#L24).

AFAIK in curl, something like 

```
curl --connect-timeout 5 \
     --max-time 10 \
     --retry 5 \
     --retry-delay 0 \
     --retry-max-time 60
```
plus [checking the exit code](https://google.github.io/styleguide/shell.xml?showone=Checking_Return_Values#Checking_Return_Values) before piping it to `tar` (or with `PIPESTATUS `) would do the trick.

**Comment by dennwc** [comment]
Seems that it's already fixed. Feel free to reopen if it's not.
