### ISSUE TITLE
New release needed :D

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/client-go#55]
Could you please release a new version?

We (@smacker and me) were stuck with a recurrent error https://travis-ci.org/src-d/gitbase-playground/jobs/383640490#L616
that was "solved" by https://github.com/bblfsh/client-go/pull/52, but it was not yet released.

**Comment by dennwc** [comment]
Done: https://github.com/bblfsh/client-go/releases/tag/v2.4.3
