### ISSUE TITLE
Differentiate `Invalid expression` error and others on tools.Filter 

### ISSUE THREAD

**Issue by smacker** [bblfsh/client-go#65]
Currently, any error happened in `tools.Filter ` returns `FatalError`.
Though `Invalid expression` means the input is wrong and a user is able to fix it.
Other errors are "internal" errors. But there is no way to differentiate them (besides comparing text of error which is super wrong).

It's needed especially for web services which uses client-go.

**Comment by dennwc** [comment]
Fixed in https://github.com/bblfsh/client-go/pull/66

**Comment by smacker** [comment]
that was fast!!! thank you.
