### ISSUE TITLE
v2 build fails

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/client-go#98]
I can no longer build v2.

https://ci.appveyor.com/project/vmarkovtsev/hercules/builds/19769146#L280

https://travis-ci.org/src-d/hercules/jobs/445897269#L1698

**Comment by dennwc** [comment]
I don't see the `Gopkg.lock` or any other dependency lock. Are you using `go get` directly? I would strongly suggest adding it.

In any case, I will remove that definition from v2.

**Comment by vmarkovtsev** [comment]
Yeah, switching to `dep` is on my list. Thanks!

**Comment by dennwc** [comment]
Should be fixed in the [latest](https://github.com/bblfsh/client-go/releases/tag/v2.8.9) v2 release.
